"""empty message

Revision ID: 883f0df7051e
Revises: 
Create Date: 2021-07-22 14:42:02.684208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883f0df7051e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortened_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortened_url_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortened_url_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shortened_url_id'], ['shortened_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortened_url_usages')
    op.drop_table('shortened_urls')
    # ### end Alembic commands ###
